# Generated by Django 5.1.1 on 2024-09-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_gas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gas',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='gas',
            name='date',
            field=models.DateField(verbose_name='Gas Up Date'),
        ),
    ]
