# Generated by Django 5.1.1 on 2024-09-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accessories_alter_gas_options_alter_gas_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Accessories',
            field=models.ManyToManyField(to='main_app.accessories'),
        ),
    ]
